### ISSUE TITLE
[Feat] 시작뷰 및 상세뷰 구현

### ISSUE THREAD

**Issue by ahra1221** [DO-SOPT-iOS-Part/KoAhRa-assignment#1]
## 🛠 Issue
- 날씨 앱 클론코딩

## 📝 To-do
🐣 기본과제
- [x] 시작화면에서 해당 나의 위치 뷰를 선택하면, 우측의 날씨 상세보기뷰로 Push되어 이동
- [x] 상세보기뷰는 수직 스크롤이 가능하고, 중간의 시간대별 날씨의 경우 수평스크롤이 가능
- [x] 하단의 리스트 보기 버튼을 선택할 경우, 시작화면으로 POP

🐥 심화과제
- [x] 여러개의 지역별 날씨 데이터를 추가 (최소 3개이상)
- [x] 위의 서치바를 이용해서 특정 지역을 검색 가능
- [x] 해당 리스트들의 개수 만큼 상세보기 뷰 에서 수평 스크롤로 이동이 가능
