### ISSUE TITLE
[Feat] 코드 리팩토링 및 상세뷰 추가 구현

### ISSUE THREAD

**Issue by ahra1221** [DO-SOPT-iOS-Part/KoAhRa-assignment#3]
## 🛠 Issue

코드 리팩토링 및 상세뷰 추가 구현

## 📝 To-do

- [x] TableView와, CollectionView를 이용한 코드 리팩토링
- [x] 상세뷰의 10일간의 일기예보 뷰 구현
- [x] 스크롤시 접혀 올라가는 헤더 구현
- [x] 그라디언트 뷰 구현
